apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster # Tên của Kafka cluster
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      # Listener 1: Cổng 9092 cho các pod bên TRONG K8s
      - name: plain
        port: 9092
        type: internal
        tls: false
      # Listener 2: Cổng 9094 cho chúng ta kết nối từ BÊN NGOÀI
      - name: external
        port: 9094
        type: nodeport # Kiểu 'nodeport' dễ nhất cho Minikube
        tls: false
    storage:
      type: ephemeral # KHÔNG lưu trữ, chạy nhẹ trên Minikube
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral # KHÔNG lưu trữ
  entityOperator:
    topicOperator: {}
    userOperator: {}
